apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: nodejsapp
    app.kubernetes.io/instance: nodejsapp-instance
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/managed-by: kubectl
  name: nodejsapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejsapp
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      containers:
        - image: 734131281465.dkr.ecr.ap-southeast-1.amazonaws.com/nodejsapp:v1
          imagePullPolicy: Always
          name: nodejsapp
          ports:
            - containerPort: 3000
