apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: nodejsapp
    app.kubernetes.io/instance: nodejsapp-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: nodejsapp
spec:
  selector:
    app: nodejsapp
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 3000
